name = "andy-game"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[site]
bucket = ".output/public"

[[d1_databases]]
binding = "DB" # 这个是在代码中使用的变量名
database_name = "andy_game_db"
database_id = "b69f94f9-402f-4ded-b0b5-40e852e6eddb"

[build]
command = "pnpm build"
watch_dir = ["src", "app", "server", "public"] 