name = "andy-games"
main = ".output/server/index.mjs"
compatibility_date = "2024-07-25"

[site]
bucket = ".output/public"

[build]
command = "pnpm build"
watch_dir = ["src", "app", "server", "public"] 