name = "andy-game"
main = ".output/server/index.mjs"
compatibility_date = "2024-01-01"

[site]
bucket = ".output/public"

[[d1_databases]]
binding = "DB" # 这个是在代码中使用的变量名
database_name = "andydb"
database_id = "85f97daa-c67a-4700-84fb-0c544b6db1e8"

[env.local]
[[env.local.d1_databases]]
binding = "DB"
database_name = "andydb"
database_id = "85f97daa-c67a-4700-84fb-0c544b6db1e8"


[build]
command = "pnpm build"
watch_dir = ["app", "functions", "public"] 