[[d1_databases]]
binding = "DB"  # 用于在代码中访问的变量名
database_name = "andydb"  # D1 数据库名称
database_id = "fbf06f0a-f30c-4d36-8bca-c6736bf439e8"  # 在 Cloudflare 仪表板中创建的 D1 ID

[build]
command = "" # 如果需要构建命令，在这里添加
output_dir = "public" # 修改为 public 目录

[site]
bucket = "public"  # 修改为 public 目录

# 添加主入口文件配置
main = "./functions/[[path]].js"